apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-from-gke
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: flask-app 
    spec:
      # 1. For running the application
      containers:
      - name: flask-app
        # TODO: <REGION>-docker.pkg.dev/<PROJECT_ID>/flask-repo/flask-app:latest (Replace these values)
        image: northamerica-northeast2-docker.pkg.dev/data-at-anz-350321/flask-repo/flask-app:latest   
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: INSTANCE_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret  
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret  
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret  
              key: database
      # 2. For running the Cloud SQL Auth proxy alongside the application
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest 
        command:
          - "/cloud_sql_proxy"
          # TODO: "-instances=<PROJECT_ID>:<REGION>:<INSTANCE_NAME>=tcp:5432" (Replace these values)
          - "-instances=data-at-anz-350321:northamerica-northeast2:sql-dev-01465918=tcp:5432"  
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        volumeMounts:
        - name: sa-volume
          mountPath: /secrets/
          readOnly: true
      volumes:
      - name: sa-volume
        secret:
          secretName: cloudsql-sa

