apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-from-k8s
spec:
  selector:
    matchLabels:
      app: flask-app  # APP_NAME
  template:
    metadata:
      labels:
        app: flask-app  # APP_NAME
    spec:
      serviceAccountName: ${KSA_NAME}  
      # 1. For running the application
      containers:
      - name: flask-app
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${folder}:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: INSTANCE_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ${DB_SECRET}
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: ${DB_SECRET}
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: ${DB_SECRET}
              key: database
      # 2. For running the Cloud SQL Auth proxy alongside the application
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest 
        command:
          - "/cloud_sql_proxy"
          - "-log_debug_stdout"
          - "-instances=${CONNECTION_NAME}=tcp:5432"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu:    "1"