# The Flask service provides a load-balancing proxy over the flask-app
# pods. By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 80  # Users may access the application through port 80
    targetPort: 8080  # Connect from port 80 to the container port 8080 